// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as dotenv } from "dotenv";
import { defineConfig } from "prisma/config";

// Load environment variables from .env.local (project convention) with .env fallback.
dotenv({ path: ".env.local" });
dotenv();

const databaseUrl = process.env["DATABASE_URL"] ?? "";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
